derlecalistir:program calistir

program:cppler main
	g++  ./lib/kontrol.o ./lib/stringKuyrukYildizKuyruk.o ./lib/stringKuyrukYildizDugum.o ./lib/stringKuyruk.o ./lib/stringDugum.o ./lib/sistem.o ./lib/Radix.o ./lib/organizma.o ./lib/organ.o ./lib/kuyrukYildizDugum.o ./lib/kuyrukKuyruk.o ./lib/intYildizKuyruk.o ./lib/intYildizDugum.o ./lib/intKuyrukYildizKuyruk.o ./lib/intKuyrukYildizDugum.o ./lib/intKuyrukDugum.o ./lib/intKuyruk.o ./lib/ikiliAramaAgaciDugum.o ./lib/ikiliAramaAgaci.o ./lib/hucre.o ./lib/Doku.o ./lib/agacKuyrukDugum.o ./lib/AgacKuyruk.o ./lib/main.o -o ./bin/program
cppler:
	g++ -I "./include" -c ./src/AgacKuyruk.cpp -o ./lib/AgacKuyruk.o
	g++ -I "./include" -c ./src/agacKuyrukDugum.cpp -o ./lib/agacKuyrukDugum.o
	g++ -I "./include" -c ./src/Doku.cpp -o ./lib/Doku.o
	g++ -I "./include" -c ./src/hucre.cpp -o ./lib/hucre.o
	g++ -I "./include" -c ./src/ikiliAramaAgaci.cpp -o ./lib/ikiliAramaAgaci.o
	g++ -I "./include" -c ./src/ikiliAramaAgaciDugum.cpp -o ./lib/ikiliAramaAgaciDugum.o
	g++ -I "./include" -c ./src/intKuyruk.cpp -o ./lib/intKuyruk.o
	g++ -I "./include" -c ./src/intKuyrukDugum.cpp -o ./lib/intKuyrukDugum.o
	g++ -I "./include" -c ./src/intKuyrukYildizDugum.cpp -o ./lib/intKuyrukYildizDugum.o
	g++ -I "./include" -c ./src/intKuyrukYildizKuyruk.cpp -o ./lib/intKuyrukYildizKuyruk.o
	g++ -I "./include" -c ./src/intYildizDugum.cpp -o ./lib/intYildizDugum.o
	g++ -I "./include" -c ./src/intYildizKuyruk.cpp -o ./lib/intYildizKuyruk.o
	g++ -I "./include" -c ./src/kuyrukKuyruk.cpp -o ./lib/kuyrukKuyruk.o
	g++ -I "./include" -c ./src/kuyrukYildizDugum.cpp -o ./lib/kuyrukYildizDugum.o
	g++ -I "./include" -c ./src/organ.cpp -o ./lib/organ.o
	g++ -I "./include" -c ./src/organizma.cpp -o ./lib/organizma.o
	g++ -I "./include" -c ./src/Radix.cpp -o ./lib/Radix.o
	g++ -I "./include" -c ./src/sistem.cpp -o ./lib/sistem.o
	g++ -I "./include" -c ./src/stringDugum.cpp -o ./lib/stringDugum.o
	g++ -I "./include" -c ./src/stringKuyruk.cpp -o ./lib/stringKuyruk.o
	g++ -I "./include" -c ./src/stringKuyrukYildizDugum.cpp -o ./lib/stringKuyrukYildizDugum.o
	g++ -I "./include" -c ./src/stringKuyrukYildizKuyruk.cpp -o ./lib/stringKuyrukYildizKuyruk.o
	g++ -I "./include" -c ./src/kontrol.cpp -o ./lib/kontrol.o
main:
	g++ -I "./include" -c ./src/main.cpp -o ./lib/main.o
calistir:
	./bin/program.exe
